[package]
name = "ferret"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
dashmap = "6.1.0"
rayon = "1.11.0"
thiserror = "2.0.16"
walkdir = { version = "2.5.0", default-features = false }
